name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 9:00 AM
    - cron: '0 9 * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: gautamkrishnar/blog-post-workflow@46af00b82fdb135b30b92fefb6e977d2627373a0
        with:
          feed_list: 'https://vladimirzdrazil.com/index.xml'