name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 9:00 AM
    - cron: "0 9 * * *"
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: gautamkrishnar/blog-post-workflow@df7a546e413f4205b922fe88c35ebe6705b2e2bd
        with:
          commit_message: "update with the latest blog posts"
          feed_list: "https://vladimirzdrazil.com/index.xml"
      - uses: gautamkrishnar/blog-post-workflow@df7a546e413f4205b922fe88c35ebe6705b2e2bd
        with:
          comment_tag_name: "TIL-POST-LIST"
          commit_message: "update with the latest TIL posts"
          feed_list: "https://vladimirzdrazil.com/til.xml"
